// Command generate produces every fixture in this directory: a test-only
// SAML IdP signing key + self-signed certificate, and synthetic SP/IdP
// SAML metadata documents that embed that certificate.
//
//	go run ./fixtures
//
// regenerates everything in place (rotating the key, so anything that
// pinned the old certificate's fingerprint needs to be updated too).
//
// ---------------------------------------------------------------------
// TEST ONLY — not a real credential.
//
// Every key this program writes is generated fresh, right here, with
// crypto/rand. None of it has ever signed anything real, none of it is
// derived from any production secret, and it is safe to commit to a public
// repository. The three consumer projects (Passwall-Sub-Panel, AlertHub,
// Report-Portal) each copy this directory's output into their own test
// configuration when they point their SAML SP at a mock IdP for CI — see
// the "TEST ONLY" banner repeated in every generated file for the same
// warning at the point of reuse.
// ---------------------------------------------------------------------
package main

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
	"log"
	"math/big"
	"os"
	"path/filepath"
	"text/template"
	"time"
)

// testOnlyBanner is prepended, as a comment, to every text fixture this
// program writes. It exists so that grep 'TEST ONLY' across a consuming
// project's tree reliably finds every copy of this material, and so nobody
// who opens one of these files in isolation mistakes it for something
// real.
const testOnlyBanner = "TEST ONLY — not a real credential. Generated by security-test-suite/fixtures/generate.go; do not use outside test/CI configuration."

// RFC 5737 documentation address space and the example.com / example.org
// reserved domains (RFC 2606) are used throughout instead of any real host
// or IP, per this suite's rule against touching real infrastructure.
const (
	idpEntityID  = "https://idp.example.com/sectest-idp/metadata"
	idpSSOURL    = "https://idp.example.com/sectest-idp/sso"
	spEntityID   = "https://sp.example.com/sectest-sp/metadata"
	spACSURL     = "https://sp.example.com/sectest-sp/saml/acs" // matches reference/{safe,vulnerable}'s POST /saml/acs, fronted by a proxy at this hostname in a real deployment
	certValidFor = 10 * 365 * 24 * time.Hour                    // 10 years: this is test fixture material, not a production cert with a real rotation policy
)

func main() {
	dir, err := os.Getwd()
	if err != nil {
		log.Fatalf("getwd: %v", err)
	}
	// Allow running as `go run ./fixtures` from the module root (the usual
	// case) or `go run generate.go` from inside fixtures/ itself.
	if filepath.Base(dir) != "fixtures" {
		dir = filepath.Join(dir, "fixtures")
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		log.Fatalf("mkdir %s: %v", dir, err)
	}

	key, certDER, cert, err := generateIdPKeyAndCert()
	if err != nil {
		log.Fatalf("generate IdP key/cert: %v", err)
	}

	keyPath := filepath.Join(dir, "idp-test-key.pem")
	certPath := filepath.Join(dir, "idp-test-cert.pem")
	idpMetaPath := filepath.Join(dir, "idp-metadata.xml")
	spMetaPath := filepath.Join(dir, "sp-metadata.xml")

	if err := writeKeyPEM(keyPath, key); err != nil {
		log.Fatalf("write %s: %v", keyPath, err)
	}
	if err := writeCertPEM(certPath, certDER); err != nil {
		log.Fatalf("write %s: %v", certPath, err)
	}
	certB64 := base64OfDER(certDER)
	if err := writeIdPMetadata(idpMetaPath, certB64); err != nil {
		log.Fatalf("write %s: %v", idpMetaPath, err)
	}
	if err := writeSPMetadata(spMetaPath); err != nil {
		log.Fatalf("write %s: %v", spMetaPath, err)
	}

	fmt.Printf("wrote fixtures (TEST ONLY, regenerated fresh every run):\n")
	fmt.Printf("  %s\n  %s\n  %s\n  %s\n", keyPath, certPath, idpMetaPath, spMetaPath)
	fmt.Printf("IdP certificate fingerprint (SHA-256): %x\n", cert.Signature[:min(8, len(cert.Signature))])
	fmt.Printf("IdP cert not-after: %s\n", cert.NotAfter.Format(time.RFC3339))
}

// generateIdPKeyAndCert creates a fresh 2048-bit RSA key and a self-signed
// certificate for it, standing in for a real SAML IdP's signing
// certificate. 2048-bit RSA matches what crewjam/saml's own test suite and
// most real IdPs (Okta, Azure AD) use for assertion signing, so a signature
// built against this fixture exercises the same code path a real IdP
// would.
func generateIdPKeyAndCert() (*rsa.PrivateKey, []byte, *x509.Certificate, error) {
	key, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return nil, nil, nil, err
	}

	serial, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	if err != nil {
		return nil, nil, nil, err
	}

	tmpl := &x509.Certificate{
		SerialNumber: serial,
		Subject: pkix.Name{
			CommonName:   "security-test-suite mock SAML IdP (TEST ONLY)",
			Organization: []string{"KazuhaHub security-test-suite fixtures"},
		},
		DNSNames:              []string{"idp.example.com"},
		NotBefore:             time.Now().Add(-1 * time.Hour),
		NotAfter:              time.Now().Add(certValidFor),
		KeyUsage:              x509.KeyUsageDigitalSignature | x509.KeyUsageCertSign,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		BasicConstraintsValid: true,
		IsCA:                  true, // self-signed leaf acting as its own root, as is normal for a SAML IdP signing cert
	}

	der, err := x509.CreateCertificate(rand.Reader, tmpl, tmpl, &key.PublicKey, key)
	if err != nil {
		return nil, nil, nil, err
	}
	cert, err := x509.ParseCertificate(der)
	if err != nil {
		return nil, nil, nil, err
	}
	return key, der, cert, nil
}

func writeKeyPEM(path string, key *rsa.PrivateKey) error {
	block := &pem.Block{
		Type:  "RSA PRIVATE KEY",
		Bytes: x509.MarshalPKCS1PrivateKey(key),
	}
	var out []byte
	out = append(out, []byte("# "+testOnlyBanner+"\n")...)
	out = append(out, pem.EncodeToMemory(block)...)
	return os.WriteFile(path, out, 0o600)
}

func writeCertPEM(path string, der []byte) error {
	block := &pem.Block{Type: "CERTIFICATE", Bytes: der}
	var out []byte
	out = append(out, []byte("# "+testOnlyBanner+"\n")...)
	out = append(out, pem.EncodeToMemory(block)...)
	return os.WriteFile(path, out, 0o644)
}

func base64OfDER(der []byte) string {
	block := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der})
	// Strip the PEM header/footer/newlines to get the bare base64 blob
	// SAML metadata's <ds:X509Certificate> element expects.
	s := string(block)
	const head = "-----BEGIN CERTIFICATE-----\n"
	const foot = "-----END CERTIFICATE-----\n"
	s = s[len(head):]
	s = s[:len(s)-len(foot)]
	out := ""
	for _, line := range splitLines(s) {
		out += line
	}
	return out
}

func splitLines(s string) []string {
	var lines []string
	start := 0
	for i, c := range s {
		if c == '\n' {
			lines = append(lines, s[start:i])
			start = i + 1
		}
	}
	if start < len(s) {
		lines = append(lines, s[start:])
	}
	return lines
}

const idpMetadataTemplate = `<!-- {{.Banner}} -->
<EntityDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata"
                   entityID="{{.EntityID}}">
  <IDPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol"
                     WantAuthnRequestsSigned="false">
    <KeyDescriptor use="signing">
      <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:X509Data>
          <ds:X509Certificate>{{.CertB64}}</ds:X509Certificate>
        </ds:X509Data>
      </ds:KeyInfo>
    </KeyDescriptor>
    <NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</NameIDFormat>
    <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
                          Location="{{.SSOURL}}"/>
    <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
                          Location="{{.SSOURL}}"/>
  </IDPSSODescriptor>
</EntityDescriptor>
`

const spMetadataTemplate = `<!-- {{.Banner}} -->
<EntityDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata"
                   entityID="{{.EntityID}}">
  <SPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol"
                    AuthnRequestsSigned="false"
                    WantAssertionsSigned="true">
    <NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</NameIDFormat>
    <AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
                               Location="{{.ACSURL}}"
                               index="0"
                               isDefault="true"/>
  </SPSSODescriptor>
</EntityDescriptor>
`

func writeIdPMetadata(path, certB64 string) error {
	t := template.Must(template.New("idp").Parse(idpMetadataTemplate))
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return t.Execute(f, struct {
		Banner, EntityID, SSOURL, CertB64 string
	}{testOnlyBanner, idpEntityID, idpSSOURL, certB64})
}

func writeSPMetadata(path string) error {
	t := template.Must(template.New("sp").Parse(spMetadataTemplate))
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return t.Execute(f, struct {
		Banner, EntityID, ACSURL string
	}{testOnlyBanner, spEntityID, spACSURL})
}
