package authenticator

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/sha256"
	"fmt"
	"sync"
)

// credentialIDLength is the number of random bytes this authenticator uses
// for a newly minted credential ID. WebAuthn places no meaning on the
// value beyond opacity and uniqueness; 32 bytes matches what real
// platform/roaming authenticators typically generate.
const credentialIDLength = 32

// credentialRecord is everything this authenticator itself must remember
// about a credential it created, to answer a later Authenticate call for
// it: its own private key (never leaves this process, exactly like a real
// authenticator's), the RP it was created for, the user handle it is
// associated with, and the signature counter it last reported.
type credentialRecord struct {
	id         []byte
	priv       *ecdsa.PrivateKey
	pubKeyCOSE []byte
	rpID       string
	userHandle []byte
	signCount  uint32
}

// Authenticator is a single software WebAuthn authenticator: one AAGUID
// (identifying "this authenticator model") holding zero or more
// discoverable ES256 credentials, each with its own key pair generated by
// crypto/rand. It is safe for concurrent use.
//
// Register and Authenticate are this type's only two operations, mirroring
// exactly the two ceremonies WebAuthn defines (§7.1, §7.2); everything
// else in this package exists only to serve those two.
type Authenticator struct {
	mu     sync.Mutex
	aaguid [16]byte
	creds  map[string]*credentialRecord // keyed by string(credentialID)
}

// New returns a fresh Authenticator with a randomly generated AAGUID and no
// credentials.
func New() (*Authenticator, error) {
	var aaguid [16]byte
	if _, err := rand.Read(aaguid[:]); err != nil {
		return nil, fmt.Errorf("authenticator: generate AAGUID: %w", err)
	}
	return &Authenticator{aaguid: aaguid, creds: make(map[string]*credentialRecord)}, nil
}

// RegistrationInput carries the parameters an honest client would read
// from the Relying Party's PublicKeyCredentialCreationOptions (the begin
// response) and its own execution context, before calling
// navigator.credentials.create().
type RegistrationInput struct {
	// RPID is the relying party ID the ceremony's begin response declared
	// (options.publicKey.rp.id). Hashed into authData.rpIdHash unless
	// overridden by WithRPID.
	RPID string
	// Origin is the origin this (simulated) page is actually running at.
	// Embedded in clientDataJSON unless overridden by WithOrigin.
	Origin string
	// Challenge is the raw challenge bytes from the begin response
	// (options.publicKey.challenge, already base64url-decoded). Embedded
	// in clientDataJSON unless overridden by WithChallenge.
	Challenge []byte
	// UserHandle is the user handle (options.publicKey.user.id, already
	// base64url-decoded) this new credential becomes associated with. A
	// later Authenticate call against this credential reports this value
	// as the assertion's userHandle unless overridden by WithUserHandle.
	UserHandle []byte
	// CrossOrigin is embedded in clientDataJSON's crossOrigin member.
	CrossOrigin bool
}

// RegistrationResult is what a successful Register call produces: the new
// credential's ID and the exact JSON body a real client would POST to the
// Relying Party's registration-finish endpoint, plus the individual pieces
// that went into it for tests that want to inspect or further mutate them.
type RegistrationResult struct {
	CredentialID      []byte
	Body              []byte // ready to POST as the finish request body
	ClientDataJSON    []byte
	AttestationObject []byte
	AuthenticatorData []byte
	PublicKeyCOSE     []byte
}

// Register performs a full registration ceremony: it generates a new ES256
// key pair, builds real authenticatorData with attested credential data and
// a "none"-format CBOR attestationObject, and returns the JSON body a
// client would POST to finish the ceremony. The credential is remembered
// (keyed by its ID) so a later Authenticate call can use it.
func (a *Authenticator) Register(in RegistrationInput, opts ...Option) (*RegistrationResult, error) {
	cfg := newCeremonyConfig(opts)

	priv, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, fmt.Errorf("authenticator: generate ES256 key: %w", err)
	}
	pubKeyCOSE, err := coseEncodePublicKey(&priv.PublicKey)
	if err != nil {
		return nil, fmt.Errorf("authenticator: encode COSE public key: %w", err)
	}

	credentialID := make([]byte, credentialIDLength)
	if _, err := rand.Read(credentialID); err != nil {
		return nil, fmt.Errorf("authenticator: generate credential ID: %w", err)
	}

	rpID := in.RPID
	if cfg.rpidOverride != nil {
		rpID = *cfg.rpidOverride
	}
	rpIDHash := sha256.Sum256([]byte(rpID))

	aaguid := a.aaguid
	if cfg.aaguidOverride != nil {
		aaguid = *cfg.aaguidOverride
	}

	counter := uint32(1)
	if cfg.counter != nil {
		counter = *cfg.counter
	}

	userPresent, userVerified := true, true
	if cfg.userPresent != nil {
		userPresent = *cfg.userPresent
	}
	if cfg.userVerified != nil {
		userVerified = *cfg.userVerified
	}

	attestedCredentialData := buildAttestedCredentialData(aaguid, credentialID, pubKeyCOSE)
	authData := buildAuthData(rpIDHash[:], userPresent, userVerified, counter, attestedCredentialData)

	attestationObject, err := buildAttestationObjectNone(authData)
	if err != nil {
		return nil, fmt.Errorf("authenticator: encode attestation object: %w", err)
	}

	origin := in.Origin
	if cfg.originOverride != nil {
		origin = *cfg.originOverride
	}
	challenge := in.Challenge
	if cfg.challengeOverride != nil {
		challenge = cfg.challengeOverride
	}
	clientDataJSON := buildClientDataJSON(ceremonyTypeCreate, challenge, origin, in.CrossOrigin)

	body, err := buildCredentialCreationResponse(credentialID, clientDataJSON, attestationObject)
	if err != nil {
		return nil, fmt.Errorf("authenticator: encode registration response: %w", err)
	}

	a.mu.Lock()
	a.creds[string(credentialID)] = &credentialRecord{
		id:         credentialID,
		priv:       priv,
		pubKeyCOSE: pubKeyCOSE,
		rpID:       in.RPID,
		userHandle: append([]byte(nil), in.UserHandle...),
		signCount:  counter,
	}
	a.mu.Unlock()

	return &RegistrationResult{
		CredentialID:      credentialID,
		Body:              body,
		ClientDataJSON:    clientDataJSON,
		AttestationObject: attestationObject,
		AuthenticatorData: authData,
		PublicKeyCOSE:     pubKeyCOSE,
	}, nil
}

// AssertionInput carries the parameters an honest client would read from
// the Relying Party's PublicKeyCredentialRequestOptions (the begin
// response) and its own execution context, before calling
// navigator.credentials.get().
type AssertionInput struct {
	// RPID is the relying party ID the ceremony's begin response declared
	// (options.publicKey.rpId). Hashed into authData.rpIdHash unless
	// overridden by WithRPID.
	RPID string
	// Origin is the origin this (simulated) page is actually running at.
	// Embedded in clientDataJSON unless overridden by WithOrigin.
	Origin string
	// Challenge is the raw challenge bytes from the begin response
	// (options.publicKey.challenge, already base64url-decoded). Embedded
	// in clientDataJSON unless overridden by WithChallenge.
	Challenge []byte
	// CredentialID selects which of this Authenticator's previously
	// registered credentials to assert with.
	CredentialID []byte
	// CrossOrigin is embedded in clientDataJSON's crossOrigin member.
	CrossOrigin bool
}

// AssertionResult is what a successful Authenticate call produces: the
// exact JSON body a real client would POST to the Relying Party's
// login-finish endpoint, plus the individual pieces that went into it.
type AssertionResult struct {
	CredentialID      []byte
	Body              []byte // ready to POST as the finish request body
	ClientDataJSON    []byte
	AuthenticatorData []byte
	Signature         []byte
	UserHandle        []byte
}

// Authenticate performs a full authentication (login) ceremony against a
// credential this Authenticator previously created via Register: it builds
// real (non-attested) authenticatorData, signs authenticatorData‖
// SHA-256(clientDataJSON) with the credential's own ES256 private key
// (never exposed outside this package), and returns the JSON body a client
// would POST to finish the ceremony.
func (a *Authenticator) Authenticate(in AssertionInput, opts ...Option) (*AssertionResult, error) {
	cfg := newCeremonyConfig(opts)

	a.mu.Lock()
	rec, ok := a.creds[string(in.CredentialID)]
	a.mu.Unlock()
	if !ok {
		return nil, fmt.Errorf("authenticator: unknown credential ID %x — Register it with this Authenticator first", in.CredentialID)
	}

	rpID := in.RPID
	if cfg.rpidOverride != nil {
		rpID = *cfg.rpidOverride
	}
	rpIDHash := sha256.Sum256([]byte(rpID))

	counter := rec.signCount + 1
	if cfg.counter != nil {
		counter = *cfg.counter
	}

	userPresent, userVerified := true, true
	if cfg.userPresent != nil {
		userPresent = *cfg.userPresent
	}
	if cfg.userVerified != nil {
		userVerified = *cfg.userVerified
	}

	authData := buildAuthData(rpIDHash[:], userPresent, userVerified, counter, nil)

	origin := in.Origin
	if cfg.originOverride != nil {
		origin = *cfg.originOverride
	}
	challenge := in.Challenge
	if cfg.challengeOverride != nil {
		challenge = cfg.challengeOverride
	}
	clientDataJSON := buildClientDataJSON(ceremonyTypeGet, challenge, origin, in.CrossOrigin)

	signature, err := signAssertion(rec.priv, authData, clientDataJSON)
	if err != nil {
		return nil, fmt.Errorf("authenticator: sign assertion: %w", err)
	}
	if cfg.corruptSignature && len(signature) > 0 {
		signature = append([]byte(nil), signature...)
		signature[len(signature)-1] ^= 0xFF
	}

	userHandle := rec.userHandle
	if cfg.userHandleOverride != nil {
		userHandle = cfg.userHandleOverride
	}

	body, err := buildCredentialAssertionResponse(rec.id, clientDataJSON, authData, signature, userHandle)
	if err != nil {
		return nil, fmt.Errorf("authenticator: encode assertion response: %w", err)
	}

	// A real authenticator always advances (or reports) its own counter
	// regardless of whether the Relying Party will go on to accept this
	// particular assertion — the RP's acceptance decision has no way to
	// reach back into the authenticator's hardware state. WithCounter lets
	// a test override this with an explicit value (including a rollback)
	// without that override silently vanishing the next call.
	a.mu.Lock()
	rec.signCount = counter
	a.mu.Unlock()

	return &AssertionResult{
		CredentialID:      rec.id,
		Body:              body,
		ClientDataJSON:    clientDataJSON,
		AuthenticatorData: authData,
		Signature:         signature,
		UserHandle:        userHandle,
	}, nil
}
